const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");

const { generateTypes } = require("../dist/generator");
const { saveRegistry } = require("../dist/core/registry");

test("generateTypes output is stable and sorted", () => {
  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "typed-fetch-generate-"));
  const registryPath = path.join(tempDir, "registry.json");
  const generatedPath = path.join(tempDir, "typed-fetch.d.ts");

  saveRegistry(registryPath, {
    version: 2,
    endpoints: {
      "GET /zeta": {
        responses: {
          "404": { kind: "object", fields: { message: { shape: { kind: "string" } } } },
        },
        meta: { seenCount: 1, lastSeenAt: "2026-02-01T00:00:00.000Z", observedPaths: [] },
      },
      "GET /alpha": {
        responses: {
          "200": { kind: "object", fields: { id: { shape: { kind: "number" } } } },
          "201": { kind: "void" },
        },
        meta: { seenCount: 2, lastSeenAt: "2026-02-01T00:00:00.000Z", observedPaths: [] },
      },
    },
  });

  const result = generateTypes({ registryPath, generatedPath });
  const expected = `/* eslint-disable */
/* This file is auto-generated by @phumudzo/typed-fetch. Do not edit manually. */

declare module "@phumudzo/typed-fetch" {
  interface TypedFetchGeneratedResponses {
    "GET /alpha": {
      200: { "id": number; };
      201: void;
    };
    "GET /zeta": {
      404: { "message": string; };
    };
  }
}

export {};
`;

  assert.equal(result.content, expected);
});
